/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package productregistration;

import java.awt.Dimension;
import java.awt.Image;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;

/**
 *
 * @author tigler
 */
public class KartaTovara extends javax.swing.JFrame {

    private int PK;
    private int addOrUpdate;
    private ListenerCloseForm listenerCloseForm;
    private String pkCost;

    public void setListenerCloseForm(ListenerCloseForm listenerCloseForm) {
        this.listenerCloseForm = listenerCloseForm;
    }

    /**
     * Creates new form KartaTovara
     */
    public KartaTovara(int PK, int addOrUpdate) {
        initComponents();
        this.PK = PK;
        this.addOrUpdate = addOrUpdate;
        //SpinnerNumberModel model = new SpinnerNumberModel(0, 0, 100000, 1);
        //jSpinnerOst.setModel(model);

        jTextFieldName.setDocument(new PlainDocument() {
            @Override
            public void insertString(int offset, String str, AttributeSet attr) throws BadLocationException {
                if (str == null) {
                    return;
                }
                if ((getLength() + str.length()) <= 30) {
                    super.insertString(offset, str, attr);
                }
            }
        });

        jTextFieldEdIz.setDocument(new PlainDocument() {
            @Override
            public void insertString(int offset, String str, AttributeSet attr) throws BadLocationException {
                if (str == null) {
                    return;
                }
                if ((getLength() + str.length()) <= 6) {
                    super.insertString(offset, str, attr);
                }
            }
        });

        if (addOrUpdate == 1 || addOrUpdate == 2) {
            ResultSet resSet = null;

            try {
                resSet = ProductRegistration.st.executeQuery("select pk_tovar,"
                        + " nametovar,ostatok,edizmer,pk_cost"
                        + " from tovar where pk_tovar=" + PK
                );
                if (resSet.next()) {
                    pkCost = resSet.getString(5);
                    jTextFieldName.setText(resSet.getString(2));
                    //jSpinnerOst.setValue(Integer.parseInt(resSet.getString(3)));
                    jTextFieldEdIz.setText(resSet.getString(4));
                }
                if (addOrUpdate == 2) {
                    jTextFieldName.setEditable(false);
                    //jSpinnerOst.setEnabled(false);
                    jSpinnerZak.setEnabled(false);
                    jSpinnerNDS.setEnabled(false);
                    jSpinnerNac.setEnabled(false);
                    jTextFieldEdIz.setEditable(false);
                }

            } catch (Exception ex) {
                System.out.println(ex);
            }
            try {
                resSet = ProductRegistration.st.executeQuery("select pk_cost,"
                        + " zakupka,nds,nacenka"
                        + " from cost where pk_cost=" + pkCost
                );
                if (resSet.next()) {
                    jSpinnerZak.setValue(Integer.parseInt(resSet.getString(2)));
                    jSpinnerNDS.setValue(Integer.parseInt(resSet.getString(3)));
                    jSpinnerNac.setValue(Integer.parseInt(resSet.getString(4)));
                }
            } catch (Exception ex) {
                System.out.println(ex);
                Logger.getLogger(KartaTovara.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldEdIz = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSpinnerZak = new javax.swing.JSpinner();
        jSpinnerNDS = new javax.swing.JSpinner();
        jSpinnerNac = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButtonOk = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Карта товара");

        jLabel1.setText("Наименование");

        jLabel3.setText("Ед.измерения");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addComponent(jTextFieldEdIz, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldEdIz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Основное", jPanel2);

        jLabel4.setText("Закупочная цена");

        jLabel5.setText("НДС");

        jLabel6.setText("Наценка");

        jLabel7.setText("руб.");

        jLabel8.setText("%");

        jLabel9.setText("%");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSpinnerNDS, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(jSpinnerNac)
                    .addComponent(jSpinnerZak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jSpinnerZak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jSpinnerNDS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jSpinnerNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Цены", jPanel1);

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Отмена");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jButtonCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOk)
                    .addComponent(jButtonCancel))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        // TODO add your handling code here:
        ResultSet resSet = null;
        try {
            String name = jTextFieldName.getText();
            String edIz = jTextFieldEdIz.getText();
            int ost, zak, nds, nac;

            try {
                //ost = Integer.parseInt(jSpinnerOst.getValue().toString());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Неверно введен остаток товара", "Неверный ввод", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            try {
                zak = Integer.parseInt(jSpinnerZak.getValue().toString());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Неверно введена закупочная цена товара", "Неверный ввод", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            try {
                nds = Integer.parseInt(jSpinnerNDS.getValue().toString());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Неверно введен остаток товара", "Неверный ввод", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            try {
                nac = Integer.parseInt(jSpinnerNac.getValue().toString());

            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Неверно введена наценка товара", "Неверный ввод", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            if (name.equals("") || edIz.equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Сначала необходимо заполнить все поля", "Сообщение", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            if (addOrUpdate == 0) {
                try {
                    resSet = ProductRegistration.st.executeQuery("insert into cost "
                            + " (zakupka,nds,nacenka)"
                            + " values('" + zak + "','" + nds + "','" + nac + "')"
                    );
                    resSet = ProductRegistration.st.executeQuery("select cost_seq.currval from dual");
                    String pkCost = null;
                    if (resSet.next()) {
                        pkCost = resSet.getString(1);
                    }
                    resSet = ProductRegistration.st.executeQuery("insert into tovar "
                            + " (nametovar,edizmer,ostatok,pk_cost)"
                            + " values('" + name + "','" + edIz + "','" + "0" + "','" + pkCost
                            + "')"
                    );
                    listenerCloseForm.event();
                    JOptionPane.showMessageDialog(rootPane, "Карта товара успешно добавлена", "Сообщение", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception ex) {
                    System.out.println(ex);
                    Logger.getLogger(KartaTovara.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(rootPane, "Не удалось добавить карту товара", "Сообщение", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
            } else {
                if (addOrUpdate == 2) {
                    this.dispose();
                    return;
                }
                try {
                    resSet = ProductRegistration.st.executeQuery("update cost set "
                            + " zakupka='" + zak + "', nds='" + nds + "', nacenka='" + nac
                            + "' where pk_cost=" + pkCost
                    );
                    resSet = ProductRegistration.st.executeQuery("update tovar set "
                            + " nametovar='" + name + "', edizmer='" + edIz + "', ostatok='" + "0"
                            + "' where pk_tovar=" + PK
                    );
                    listenerCloseForm.event();
                    JOptionPane.showMessageDialog(rootPane, "Карта товара успешно изменена", "Сообщение", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception ex) {
                    System.out.println(ex);
                    Logger.getLogger(KartaTovara.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(rootPane, "Не удалось изменить запись о поставщике", "Сообщение", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
            }
            this.dispose();
        } catch (Exception ex) {
            System.out.println(ex);
            Logger.getLogger(KartaTovara.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "Не удалось считать поля", "Ошибка", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KartaTovara.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KartaTovara.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KartaTovara.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KartaTovara.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KartaTovara(0, 0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinnerNDS;
    private javax.swing.JSpinner jSpinnerNac;
    private javax.swing.JSpinner jSpinnerZak;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldEdIz;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
}
