/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package productregistration;

import com.toedter.calendar.JTextFieldDateEditor;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author tigler
 */
public class StrAkt extends javax.swing.JFrame {

    private int PK;
    private int addOrUpdate;
    private ListenerCloseForm listenerCloseForm;
    ArrayList<String> pkTovar;
    ArrayList<String> valuesTovar;
    int pkAkt;

    public void setListenerCloseForm(ListenerCloseForm listenerCloseForm) {
        this.listenerCloseForm = listenerCloseForm;
    }

    /**
     * Creates new form StrSchetFact
     */
    public StrAkt(int PK, int addOrUpdate, int pkAkt) {
        initComponents();
        pkTovar = new ArrayList<>();
        valuesTovar = new ArrayList<>();
        this.PK = PK;
        this.addOrUpdate = addOrUpdate;
        this.pkAkt = pkAkt;
        ResultSet resSet = null;
        try {
            resSet = ProductRegistration.st.executeQuery("select pk_tovar,"
                    + " nametovar from tovar"
            );
            while (resSet.next()) {
                pkTovar.add(resSet.getString(1));
                valuesTovar.add(resSet.getString(2));
            }
            jComboBoxTovar.setModel(new DefaultComboBoxModel(valuesTovar.toArray()));
            jComboBoxTovar.setSelectedIndex(-1);
        } catch (Exception ex) {
            System.out.println(ex);
            Logger.getLogger(KartaTovara.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (addOrUpdate == 1) {
            try {
                resSet = ProductRegistration.st.executeQuery("select strvozvrat.count,strvozvrat.pk_tovar"
                        + " from strvozvrat"
                        + " where strvozvrat.pk_stract=" + PK
                );
                if (resSet.next()) {
                    jSpinnerCount.setValue(Integer.parseInt(resSet.getString(1)));

                    for (int i = 0; i < pkTovar.size(); i++) {
                        if (pkTovar.get(i).equals(resSet.getString(2))) {
                            jComboBoxTovar.setSelectedIndex(i);
                            break;
                        }
                    }
                }
            } catch (Exception ex) {
                System.out.println(ex);
                Logger.getLogger(KartaTovara.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonOk = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jSpinnerCount = new javax.swing.JSpinner();
        jComboBoxTovar = new javax.swing.JComboBox<>();
        jLabelEI = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCost = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Строка акта-возврата");
        setResizable(false);

        jLabel1.setText("Товар");

        jLabel2.setText("Количество");

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Отмена");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jSpinnerCount.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jSpinnerCountMouseWheelMoved(evt);
            }
        });
        jSpinnerCount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jSpinnerCountMousePressed(evt);
            }
        });

        jComboBoxTovar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTovarActionPerformed(evt);
            }
        });

        jLabelEI.setText("еи");

        jLabel4.setText("Сумма");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jButtonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(jButtonCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxTovar, 0, 231, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSpinnerCount)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelEI)
                                .addGap(6, 6, 6))
                            .addComponent(jTextFieldCost))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxTovar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jSpinnerCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEI))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOk)
                    .addComponent(jButtonCancel))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        // TODO add your handling code here:
        try {
            int count = 0;
            try {
                count = Integer.parseInt(jSpinnerCount.getValue().toString());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, "Не удалось считать количество", "Сообщение", JOptionPane.INFORMATION_MESSAGE);
                System.out.println(ex);
                Logger.getLogger(KartaTovara.class.getName()).log(Level.SEVERE, null, ex);
                return;
            }
            if (addOrUpdate == 0) {
                ResultSet resSet = ProductRegistration.st.executeQuery("insert into strvozvrat(count,pk_tovar,pk_actvozvrat,pk_cost)"
                        + " values('" + count + "','" + pkTovar.get(jComboBoxTovar.getSelectedIndex()) + "','" + pkAkt + "','0')"
                );
            } else {
                ResultSet resSet = ProductRegistration.st.executeQuery("update strvozvrat set count='" + count
                        + "',pk_tovar='" + pkTovar.get(jComboBoxTovar.getSelectedIndex()) + "' where pk_stract=" + PK
                );
            }
            listenerCloseForm.event();
            this.dispose();
        } catch (Exception ex) {
            System.out.println(ex);
            Logger.getLogger(KartaTovara.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jComboBoxTovarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTovarActionPerformed
        // TODO add your handling code here:
        try {
            
            ResultSet resSet = ProductRegistration.st.executeQuery("select cost.zakupka,cost.nds,cost.nacenka,tovar.edizmer"
                    + " from tovar "
                    + " inner join cost on cost.PK_cost=tovar.PK_cost"
                    + " where tovar.pk_tovar=" + pkTovar.get(jComboBoxTovar.getSelectedIndex())
            );
            
            if (resSet.next()) {
                jLabelEI.setText(resSet.getString(4));
                double zakupka = Double.valueOf(resSet.getString(1));
                double nds = Double.valueOf(resSet.getString(2));
                double nacenka = Double.valueOf(resSet.getString(3));
                double snds = zakupka / 100 * nds;
                double snacenka = zakupka / 100 * nacenka;
                double itog = zakupka + snds + snacenka;
                String cost = String.format(Locale.US, "%.2f", itog);
                double summa = Double.valueOf(cost) * Double.valueOf(jSpinnerCount.getValue().toString());

                String sum = String.format(Locale.US, "%.2f", summa);
                jTextFieldCost.setText(sum);
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jComboBoxTovarActionPerformed

    private void jSpinnerCountMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jSpinnerCountMouseWheelMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_jSpinnerCountMouseWheelMoved

    private void jSpinnerCountMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSpinnerCountMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jSpinnerCountMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StrSchetFact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StrSchetFact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StrSchetFact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StrSchetFact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StrSchetFact(0, 0, 0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JComboBox<String> jComboBoxTovar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelEI;
    private javax.swing.JSpinner jSpinnerCount;
    private javax.swing.JTextField jTextFieldCost;
    // End of variables declaration//GEN-END:variables

}
